### ISSUE TITLE
How do I cite this repo in a paper?

### ISSUE THREAD

**Issue by DigitalGabriele** [oysstu/imcpy#45]
Is there a specific paper I should cite or do I just cite the GitHub repo?

**Comment by oysstu** [comment]
There are no publications specifically for this python interface. The most important citations would be for DUNE, IMC and the LSTS toolchain. If you want to acknowledge the python interface specifically a reference to the Github repository would be the best approach.

**Comment by DigitalGabriele** [comment]
This is what I used:

```
@misc{imcpy,
  author = {Sture, {\O}ystein},
  title = {imcpy},
  year = {2023},
  publisher = {GitHub},
  note = {Retrieved October 17, 2023 from https://github.com/oysstu/imcpy}
}
```

**Comment by oysstu** [comment]
That's perfect. Good luck on your publication, good to see that it's useful :thumbsup:.
