### ISSUE TITLE
Update readme with correct command for cloning

### ISSUE THREAD

**Issue by nordam** [oysstu/imcpy#46]
Hi,

I suggest changing the following line from the readme file

```
git clone --recursive git://github.com/oysstu/imcpy.git
```

to

```
git clone --recursive git@github.com/oysstu/imcpy.git
```
or
```
git clone --recursive https://github.com/oysstu/imcpy.git
```

The first line gives (me, at least) a timeout error, while the second and third work. It seems github no longer allows connections via the ```git://``` protocol (https://github.blog/2021-09-01-improving-git-protocol-security-github/).

**Comment by oysstu** [comment]
Good point, I've updated it now. I think it makes more sense to clone via https in the readme anyway.
